name: Build and Deploy Static Website

on:
  push:
    branches: [main]
    paths: 
      - 'Static_Website/**'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    # unshallow git clone
    - run: |
        git fetch --prune --unshallow
        
# 


# jobs:
#   build-linux:
#     name: Build linux
#     runs-on: ubuntu-latest
#     strategy:
#       max-parallel: 5
#     env:
#     # bucket name, region, cloudfront distribution id
#       BUCKET: oluwaseunadeyo.com.ng
#       DIST: build
#       REGION: eu-west-1
#       DIST_ID: EWF2XRZWNJ64E

#     steps:
#     - name: Checkout
#       uses: actions/checkout@v2
        
    # - name: Configure AWS credential
    #   uses: aws-actions/configure-aws-credentials@v1
    #   with:
    #     aws-access-key-id: ${{ secrets.ACCESS_KEY }}
    #     aws-secret-access-key: ${{ secrets.SECRET_KEY }}
    #     aws-region: ${{ env.REGION }}

    # - name: Copy files to S3
    #   run: |
    #     aws s3 sync --delete ${{ env.DIST }} ${{ env.BUCKET }}
   
    # # - name: Invalidate cloudfront cache
    # #   run: |
    # #     aws cloudfront create-invalidation \
    # #       --distribution-id ${{ env.DIST_ID }} \
    # #       --paths "/*"
